// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Poker.Models;

#nullable disable

namespace Poker.Migrations
{
    [DbContext(typeof(PokerContext))]
    partial class PokerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("Poker.Models.Card", b =>
                {
                    b.Property<string>("Card1")
                        .HasColumnType("TEXT")
                        .HasColumnName("card");

                    b.HasKey("Card1")
                        .HasName("Card_pk");

                    b.ToTable("Card", (string)null);
                });

            modelBuilder.Entity("Poker.Models.CardFrontSkin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Card")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("card");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("filename");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("CardFrontSkin_pk");

                    b.HasIndex("Card");

                    b.ToTable("CardFrontSkin", (string)null);
                });

            modelBuilder.Entity("Poker.Models.CardReverseSkin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("filename");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("CardReverseSkin_pk");

                    b.ToTable("CardReverseSkin", (string)null);
                });

            modelBuilder.Entity("Poker.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Balance")
                        .HasColumnType("INTEGER")
                        .HasColumnName("balance");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.HasKey("Id")
                        .HasName("Player_pk");

                    b.HasIndex(new[] { "Email" }, "UQ_Player_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "Name" }, "UQ_Player_Name")
                        .IsUnique();

                    b.ToTable("Player", (string)null);
                });

            modelBuilder.Entity("Poker.Models.PlayerCases", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Player_id");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER")
                        .HasColumnName("number");

                    b.HasKey("PlayerId")
                        .HasName("PlayerCase_pk");

                    b.ToTable("PlayerCases", (string)null);
                });

            modelBuilder.Entity("Poker.Models.PlayerEquippedFaceSkin", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Player_id");

                    b.Property<string>("Card")
                        .HasColumnType("TEXT")
                        .HasColumnName("card");

                    b.Property<int>("SkinId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Skin_id");

                    b.HasKey("PlayerId", "Card")
                        .HasName("PlayerEquippedFaceSkin_pk");

                    b.HasIndex("Card");

                    b.HasIndex("PlayerId", "SkinId");

                    b.ToTable("PlayerEquippedFaceSkin", (string)null);
                });

            modelBuilder.Entity("Poker.Models.PlayerEquippedReverseSkin", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Player_id");

                    b.Property<int>("SkinId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Skin_id");

                    b.HasKey("PlayerId")
                        .HasName("PlayerEquippedReverseSkin_pk");

                    b.HasIndex("PlayerId", "SkinId");

                    b.ToTable("PlayerEquippedReverseSkin", (string)null);
                });

            modelBuilder.Entity("Poker.Models.PlayerOwnedFaceSkin", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Player_id");

                    b.Property<int>("SkinId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Skin_id");

                    b.HasKey("PlayerId", "SkinId")
                        .HasName("PlayerOwnedFaceSkin_pk");

                    b.HasIndex("SkinId");

                    b.ToTable("PlayerOwnedFaceSkin", (string)null);
                });

            modelBuilder.Entity("Poker.Models.PlayerOwnedReverseSkin", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Player_id");

                    b.Property<int>("SkinId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Skin_id");

                    b.HasKey("PlayerId", "SkinId")
                        .HasName("PlayerOwnedReverseSkin_pk");

                    b.HasIndex("SkinId");

                    b.ToTable("PlayerOwnedReverseSkin", (string)null);
                });

            modelBuilder.Entity("Poker.Models.PlayerTable", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Player_id");

                    b.Property<int>("TableBalance")
                        .HasColumnType("INTEGER")
                        .HasColumnName("table_balance");

                    b.Property<string>("TableJoinCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Table_joinCode");

                    b.HasKey("PlayerId")
                        .HasName("PlayerTable_pk");

                    b.HasIndex("TableJoinCode");

                    b.ToTable("PlayerTable", (string)null);
                });

            modelBuilder.Entity("Poker.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Player_id");

                    b.Property<bool>("Revoked")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revoked");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("RefreshToken_pk");

                    b.HasIndex("PlayerId");

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("Poker.Models.Table", b =>
                {
                    b.Property<string>("JoinCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("join_code");

                    b.Property<int>("BuyIn")
                        .HasColumnType("INTEGER")
                        .HasColumnName("buy_in");

                    b.HasKey("JoinCode")
                        .HasName("Table_pk");

                    b.ToTable("Table", (string)null);
                });

            modelBuilder.Entity("Poker.Models.CardFrontSkin", b =>
                {
                    b.HasOne("Poker.Models.Card", "CardNavigation")
                        .WithMany("CardFrontSkins")
                        .HasForeignKey("Card")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("CardFrontSkin_Card");

                    b.Navigation("CardNavigation");
                });

            modelBuilder.Entity("Poker.Models.PlayerCases", b =>
                {
                    b.HasOne("Poker.Models.Player", "Player")
                        .WithOne("PlayerCases")
                        .HasForeignKey("Poker.Models.PlayerCases", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Poker.Models.PlayerEquippedFaceSkin", b =>
                {
                    b.HasOne("Poker.Models.Card", "CardNavigation")
                        .WithMany("PlayerEquippedFaceSkins")
                        .HasForeignKey("Card")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("PlayerEquippedFaceSkin_Card");

                    b.HasOne("Poker.Models.PlayerOwnedFaceSkin", "PlayerOwnedFaceSkin")
                        .WithMany("PlayerEquippedFaceSkins")
                        .HasForeignKey("PlayerId", "SkinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("PlayerEquippedFaceSkin_PlayerOwnedFaceSkin");

                    b.Navigation("CardNavigation");

                    b.Navigation("PlayerOwnedFaceSkin");
                });

            modelBuilder.Entity("Poker.Models.PlayerEquippedReverseSkin", b =>
                {
                    b.HasOne("Poker.Models.PlayerOwnedReverseSkin", "PlayerOwnedReverseSkin")
                        .WithMany("PlayerEquippedReverseSkins")
                        .HasForeignKey("PlayerId", "SkinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerOwnedReverseSkin");
                });

            modelBuilder.Entity("Poker.Models.PlayerOwnedFaceSkin", b =>
                {
                    b.HasOne("Poker.Models.Player", "Player")
                        .WithMany("PlayerOwnedFaceSkins")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poker.Models.CardFrontSkin", "Skin")
                        .WithMany("PlayerOwnedFaceSkins")
                        .HasForeignKey("SkinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Skin");
                });

            modelBuilder.Entity("Poker.Models.PlayerOwnedReverseSkin", b =>
                {
                    b.HasOne("Poker.Models.Player", "Player")
                        .WithMany("PlayerOwnedReverseSkins")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poker.Models.CardReverseSkin", "Skin")
                        .WithMany("PlayerOwnedReverseSkins")
                        .HasForeignKey("SkinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Skin");
                });

            modelBuilder.Entity("Poker.Models.PlayerTable", b =>
                {
                    b.HasOne("Poker.Models.Player", "Player")
                        .WithOne("PlayerTable")
                        .HasForeignKey("Poker.Models.PlayerTable", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poker.Models.Table", "TableJoinCodeNavigation")
                        .WithMany("PlayerTables")
                        .HasForeignKey("TableJoinCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("TableJoinCodeNavigation");
                });

            modelBuilder.Entity("Poker.Models.RefreshToken", b =>
                {
                    b.HasOne("Poker.Models.Player", "Player")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Poker.Models.Card", b =>
                {
                    b.Navigation("CardFrontSkins");

                    b.Navigation("PlayerEquippedFaceSkins");
                });

            modelBuilder.Entity("Poker.Models.CardFrontSkin", b =>
                {
                    b.Navigation("PlayerOwnedFaceSkins");
                });

            modelBuilder.Entity("Poker.Models.CardReverseSkin", b =>
                {
                    b.Navigation("PlayerOwnedReverseSkins");
                });

            modelBuilder.Entity("Poker.Models.Player", b =>
                {
                    b.Navigation("PlayerCases");

                    b.Navigation("PlayerOwnedFaceSkins");

                    b.Navigation("PlayerOwnedReverseSkins");

                    b.Navigation("PlayerTable");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Poker.Models.PlayerOwnedFaceSkin", b =>
                {
                    b.Navigation("PlayerEquippedFaceSkins");
                });

            modelBuilder.Entity("Poker.Models.PlayerOwnedReverseSkin", b =>
                {
                    b.Navigation("PlayerEquippedReverseSkins");
                });

            modelBuilder.Entity("Poker.Models.Table", b =>
                {
                    b.Navigation("PlayerTables");
                });
#pragma warning restore 612, 618
        }
    }
}
